/**
 * cppic_runtime.h - runtime for C generated by cppic (C++->C for PIC18).
 *
 * Two build modes:
 *   - CPPIC_HOST_SIM : desktop simulation. SFRs such as PORTB/TRISB become
 *     plain volatile globals so the emitted C can be compiled and run with
 *     any host C compiler for testing / CI.
 *   - SDCC target    : real PIC18. SFRs are declared as SDCC __sfr / biu
 *     memory locations matching the selected device.
 *
 * The runtime also ships a small self-contained heap (see cppic_runtime.c)
 * used to implement C++ `new` / `delete` on both the simulator and the real
 * chip.  The transpiler lowers `new T` to cppic_malloc(sizeof(T)) and
 * `delete p` to cppic_free(p).
 *
 * This header is emitted by the transpiler and included by generated code.
 */
#ifndef CPPIC_RUNTIME_H
#define CPPIC_RUNTIME_H

#include <stdint.h>

#if defined(CPPIC_HOST_SIM)

/* ------------------------------------------------------------------- */
/* Desktop simulation                                                   */
/* ------------------------------------------------------------------- */
typedef volatile uint8_t cppic_port_t;
typedef volatile uint8_t cppic_tris_t;

extern uint8_t cppic_PORTB;
extern uint8_t cppic_TRISB;
extern uint8_t cppic_PORTA;
extern uint8_t cppic_TRISA;
extern uint8_t cppic_PORTC;
extern uint8_t cppic_TRISC;

/* SFR names used by PIC18 C++ sketches.  Each maps 1:1 to an
 * emulated memory cell so generated `PORTB = ...` code works as-is. */
#define PORTB cppic_PORTB
#define TRISB cppic_TRISB
#define PORTA cppic_PORTA
#define TRISA cppic_TRISA
#define PORTC cppic_PORTC
#define TRISC cppic_TRISC

/* Simple busy-wait; loop count calibrated ~1 cycle per tick on SDCC.
 * On the host it just burns time. */
static inline void cppic_delay_cycles(uint16_t n) {
    volatile uint16_t i = n;
    while (i) --i;
}
#define _delay_ms(ms) cppic_delay_cycles((uint16_t)((ms) * 1000u))

#else /* SDCC / PIC18 target (default) */

/* ------------------------------------------------------------------- */
/* Real PIC18.  SFRs as SDCC __sfr registers when building with sdcc
 * for a PIC18.  Adjust the device header below for the target chip. */
#ifdef __SDCC

#include <pic18.h>  /* SDCC device header: PORTB, TRISB, ... */

#else

/* Fallback for non-SDCC toolchains targeting PIC18 (e.g. XC8-style). */
#ifdef __XC8
#include <xc.h>
#endif

#endif /* __SDCC */

#endif /* CPPIC_HOST_SIM */

/* ------------------------------------------------------------------- */
/* Heap  (implements C++ new / delete)                                  */
/* ------------------------------------------------------------------- */
/* Returns a pointer to `size` bytes of memory, or 0 when the heap is
 * exhausted.  Memory is 4-byte aligned on hosts. */
void* cppic_malloc(unsigned int size);
void cppic_free(void* p);

#endif /* CPPIC_RUNTIME_H */
